name: Publish Snapshot

on:
  push:
    branches:
    - respark

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - respark
    steps:
    - name: Checkout Spark repository
      uses: actions/checkout@master
      with:
        ref: ${{ matrix.branch }}
    - name: Cache Maven local repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: snapshot-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          snapshot-maven-
    - name: Install Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build snapshot
      run: |
        ./dev/make-distribution.sh --name respark --tgz "-Phadoop-2.7,hive,hive-thriftserver,mesos,yarn" -B
    - name: Delete
      uses: ame-yu/action-delete-latest-release@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Snapshot ${{ github.sha }}
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./spark-2.4.0-respark-bin-respark.tgz
        asset_name: spark-2.4.0-respark-bin-respark.tgz
        asset_content_type: application/gzip
